# Generated by Django 3.0.7 on 2020-07-03 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_title', models.CharField(max_length=100)),
                ('project_description', models.CharField(max_length=350)),
                ('project_image', models.ImageField(upload_to='portfolio/images')),
                ('project_url', models.URLField(blank=True)),
            ],
        ),
    ]
