# Generated by Django 3.0.7 on 2020-07-03 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='project_description',
            new_name='project_Description',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='project_image',
            new_name='project_Image',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='project_title',
            new_name='project_Title',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='project_url',
            new_name='project_URL',
        ),
    ]
